[topology]
    [topology.sender]
        name = "18.26.5.163"
        ifaces = [{dev = "enp4s0", addr = "18.26.5.163"}]
    [topology.inbox]
        name = "18.26.5.158"
        user = "akshay"
        ifaces = [
            {dev = "enp4s0", addr = "18.26.5.158"},
            {dev = "enp1s0", addr = "18.26.5.160"},
        ]
        listen_port = 28316
    [topology.outbox]
        name = "pd2.csail.mit.edu"
        self = true
        ifaces = [{dev = "em1", addr = "18.26.5.2"}]
    [topology.receiver]
        name = "pd2.csail.mit.edu"
        ifaces = [{dev = "em2", addr = "18.26.5.2"}]

[sysctl]
"net.ipv4.tcp_rmem" = "2048000 2048000 12582912"
"net.ipv4.tcp_wmem" = "2048000 2048000 12582912"
"net.core.wmem_max" = "12582912"
"net.core.rmem_max" = "12582912"

[parameters]
initial_sample_rate = 128
bg_port_start = 5000
qdisc_buf_size = "15mbit"

[structure]
bundler_root = "~/bundler-script"

[distributions]
CAIDA_CDF = "~/bundler-script/distributions/CAIDA_CDF"

[ccp]
    [ccp.nimbus]
        repo = "https://github.com/ccp-project/nimbus.git"
        branch = "queue-control"
        commit = "latest"
        language = "rust"
        target = "target/debug/nimbus"
        [ccp.nimbus.args]
            bw_est_mode = "false"
            bundler_qlen_alpha = "100"
            bundler_qlen_beta = "10000"
            delay_mode = "Nimbus"
            use_switching = "true"
            flow_mode = "XTCP"
            loss_mode = "Bundle"
    [ccp.const]
        repo = "https://github.com/ccp-project/const.git"
        branch = "master"
        commit = "latest"
        language = "rust"
        target = "target/release/ccp_const"

[experiment]
seed      = [0, 17, 26, 28, 41, 62, 67, 68, 88, 99]
sch       = ['sfq', 'fifo']
alg       = [
    { name = 'nobundler' },
    { 
        name = 'nimbus',
        bundler_qlen = ["50", "100"]
    }
]
rate      = [96]
rtt       = [50]
bdp       = [2]
bundle_traffic = [
    [
        {source = 'poisson', conns = 200, reqs = 30000, alg = 'reno', dist = 'CAIDA_CDF', backlogged = 0, load = '7/8', start_delay = 0}
    ]
]
cross_traffic = [
    [],
    [
        {source = 'iperf', alg = 'cubic', flows = 1, length = 60, port = 8002, start_delay = 5},
    ]
    #[
    #    {source = 'iperf', alg = 'cubic', flows = 2, length = 60, port = 8002, start_delay = 5},
    #],
    #[
    #    {source = 'iperf', alg = 'cubic', flows = 5, length = 120, port = 8002, start_delay = 5},
    #]
]
