[topology]
    [topology.local] 
        name = "pd6.csail.mit.edu"
    [topology.sender]
        name = "pd1.csail.mit.edu"
        ifaces = [{dev = "em2", addr = "192.168.1.1"}]
    [topology.inbox]
        name = "pd6.csail.mit.edu"
        ifaces = [
            {dev = "em2", addr = "192.168.1.6"},
            {dev = "10gp1", addr = "10.1.1.6"},
        ]
        listen_port = 28316
    [topology.outbox]
        name = "pd5.csail.mit.edu"
        ifaces = [{dev = "10gp1", addr = "10.1.1.6"}]
    [topology.receiver]
        name = "pd5.csail.mit.edu"
        ifaces = [{dev = "10gp1", addr = "10.1.1.5"}]

[parameters]
initial_sample_rate = 128
bg_port_start = 5000
qdisc_buf_size = "15mbit"

[structure]
bundler_root = "~/bundler-scripts"
etg_dir = "~/empirical-traffic-gen"
etg_client = "bin/client"
etg_server = "run-servers.py"
iperf_path = "~/iperf/src/iperf"
bundler_dir = "~/bundler"
inbox_target = "target/debug/inbox"
outbox_target = "target/debug/outbox"

[distributions]
CAIDA_CDF = "~/bundler-scripts/CAIDA_CDF"

[ccp]
#    [ccp.copa]
#        repo = "https://github.com/akshayknarayan/ccp_copa.git"
#        branch = "rate_only"
#        commit = "latest"
#        language = "rust"
#        target = "target/debug/copa"
#        [ccp.copa.args]
#            delta_mode = "NoTCP"
#            default_delta = 0.125
    [ccp.nimbus]
        repo = "https://github.com/ccp-project/nimbus.git"
        branch = "null_xtcp"
        commit = "latest"
        language = "rust"
        target = "target/debug/nimbus"
        [ccp.nimbus.args]
            use_switching = "false"
            flow_mode = "XTCP"
            loss_mode = "Bundle"
            bw_est_mode = "false"
    [ccp.const]
        repo = "https://github.com/akshayknarayan/ccp_const_algorithm.git"
        branch = "master"
        commit = "latest"
        language = "rust"
        target = "target/release/ccp_example_alg"

[experiment]
#seed      = [0, 17, 26, 28, 41, 62, 67, 68, 88, 99]
seed      = [0]
sch       = ['fifo']
alg       = ['nimbus']
rate      = [96]
rtt       = [50]
bdp       = [3]
bundle_traffic = [[
    {source = 'iperf', alg = 'cubic', flows = 1, length = 40, port = 5000, start_delay = 0}
#example poisson : { source = 'poisson', conns = 200, reqs = 10000, alg = 'reno', backlogged = 1, dist = 'CAIDA_CDF', load = '7/8' }
]]
cross_traffic = [[
    {source = 'cbr', length = 30, port = 8001, rate = 1000000, start_delay = 10}
    #{source = 'iperf', alg = 'cubic', flows = 1, length = 10, port = 5002}
]]
